version: '3'

services:
  pulp-docker:
    image: hpretl/iic-osic-tools:pulp
    user: "${UID}:${GID}"
    volumes:
      - ./:/fosic/designs/croc
    stdin_open: true
    tty: true
    working_dir: /fosic/designs/croc
    entrypoint: /bin/bash